# Generated by Django 2.2.6 on 2020-05-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dap_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='UserInfo',
        ),
    ]
