# Generated by Django 2.2.6 on 2020-06-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dap_api', '0002_auto_20200519_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.CharField(max_length=10),
        ),
    ]
