# Generated by Django 2.2.6 on 2020-06-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dap_api', '0004_auto_20200605_1835'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='UserInfo',
        ),
    ]
