# Generated by Django 3.0.6 on 2020-06-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dap_api', '0005_auto_20200605_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestList',
            fields=[
                ('testId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('testCode', models.CharField(max_length=224)),
                ('testDate', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dap_api.UserInfo')),
            ],
            options={
                'db_table': 'TestList',
            },
        ),
        migrations.CreateModel(
            name='DepressionTest',
            fields=[
                ('testId', models.ForeignKey(max_length=224, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dap_api.TestList')),
                ('testPoint', models.IntegerField()),
            ],
            options={
                'db_table': 'DepressionTest',
            },
        ),
    ]
